### ISSUE TITLE
Generated cxx-objc-protocols.h includes AppKit only

### ISSUE THREAD

**Issue by tptee** [sandym/swiftpp#5]
Hi there,

Any way to include UIKit instead of AppKit in the generated headers? I'd love to try this project out against Facebook's new ComponentKit, an Objective-C++ iOS library. Didn't know if iOS is supported yet.

Thanks!

**Comment by sandym** [comment]
Hi, you're right, I shouldn't assume AppKit only, there is no reason for this not to work with iOS. 
For now, in the swiftpp project, you can change it manually in "SwiftppObjcTemplates.h".

I'll add that to my do to list...

**Comment by metabren** [comment]
@tptee Did you get anywhere with this?  I'm itching to use ComponentKit in a Swift app.

**Comment by sandym** [comment]
Just pushed something, instead of #import ing AppKit, it now inspect the ObjC types needed for the converters and forward declared them. As in "@class NSSometing;", so no forced #import, should work for iOS and OS X.
