### ISSUE TITLE
Lost swiftpp.xcodeproj in that last commit??

### ISSUE THREAD

**Issue by samscam** [sandym/swiftpp#9]
Looks like you deleted the swiftpp.xcodeproj in your last commit ([60905f0](https://github.com/sandym/swiftpp/commit/60905f089bf86c8730c76aa55054621e720c78dc))

**Comment by sandym** [comment]
I did, the build system now uses cmake. Run 'cmake -G Xcode' to generate the Xcode project.
I'm in the middle of major changes (as time permit). Performance improvement but also Linux support, so an Xcode project wasn't up to the task anymore. Also, llvm/clang build system is cmake based so it's easier to track changes in those.

**Comment by samscam** [comment]
Ok, thanks. That wasn't immediately obvious. I'll call that closed but do please update the readme.
